### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by jjmmii** [vmaffei/dada2_to_picrust#12]
Hi vmaffei, it's me again. I am on Part 3 now and got this error while running predict_traits.py:
```
Traceback (most recent call last):
  File "/usr/local/bin/predict_traits.py", line 451, in <module>
    main()
  File "/usr/local/bin/predict_traits.py", line 203, in main
    confidence=0.95)
  File "/usr/local/lib/python2.7/dist-packages/picrust/predict_traits.py", line 894, in get_brownian_motion_param_from_confidence_intervals
    if not variances:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Note that in my /usr/local/lib/python2.7/dist-packages/picrust/predict_traits.py lines 894-895:
```
if not variances:
    raise ValueError("Example variances could not be calculated for CIs. There may not be any cases of tip pairs where one has known and the other unknown trait values.")
```
the error emitted isn't the one in line 895.
Have you got this error before? I found a [discussion on SO](https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous), wondering if I should modify the code according to their suggestion, but more probable is that something is wrong with my input.

May I ask if you have the seqtab.nochim.robj file you used for the benchmarking? Then I can confirm it's the problem with my data.

**Comment by vmaffei** [comment]
Hey jjmmii, I have actually. Update PICRUSt to the latest version, and that should fix the issue!  

Here's my current setup for reference:

biom-format (2.1.6)
cogent (1.5.3)
h5py (2.7.0)
**numpy (1.13.3)**
pandas (0.21.0)
**PICRUSt (1.1.2.dev0)**
scipy (1.0.0)

**Comment by jjmmii** [comment]
Yes! I updated PICRUSt and it works now! Thanks again! :)

**Comment by vmaffei** [comment]
Awesome! No problem!
