### ISSUE TITLE
Batched trait prediction is incomplete

### ISSUE THREAD

**Issue by fanli-gcb** [vmaffei/dada2_to_picrust#15]
I have a (KEGG) trait table with 6909 traits from the PICRUSt precomputed file (ko_13_5_precalculated.tab.gz):
```
head -n1 ${PROJECT_DIR}/format/KEGG/trait_table.tab | wc -w
```

> 6910

Using the batched trait prediction code:
```
BATCH=2000
for ((i=2, j=$BATCH; j<=$(head -n 1 ${PROJECT_DIR}/format/KEGG/trait_table.tab | wc -w); i=i+$BATCH, j=j+$BATCH));
do
	echo "$i - $j IDs"
done
```
returns:

> 2 - 2000 IDs
> 2002 - 4000 IDs
> 4002 - 6000 IDs
> 
So IDs 2001, 4001, and 6001-6909 are all missing. I originally noticed this when I tried to use this custom ko_precomputed.tab file as input to another program and it complained that the KEGG metadata didn't have the same number of fields as the table itself.

Here's a fix:
```
BATCH=2000
for ((i=2, j=$((BATCH+1)); j<=$(head -n 1 ${PROJECT_DIR}/format/KEGG/trait_table.tab | wc -w); i=i+$BATCH, j=j+$BATCH));
do
	echo "$i - $j"
done
j=$(head -n 1 ${PROJECT_DIR}/format/KEGG/trait_table.tab | wc -w)
echo "$i - $j"
```

> 2 - 2001
> 2002 - 4001
> 4002 - 6001
> 6002 - 6910

The three `cat`, `cat`, and `predict_traits.py` lines don't change, just the looping structure. I'm no expert with bash so couldn't find a cleaner way using something like a `do-while`.

**Comment by vmaffei** [comment]
Thanks so much, @fanli-gcb , for posting this and working out a fix! I went ahead and posted the changes to the pipeline since quite a few people will need to use Part 5. I’ll have a chance to actually run the edited version myself late next week (currently away from a proper computer), but I wanted to get something out there ASAP. Please let me know if you run into any errors/problems again (and if the modified Part 5 looks correct)!

**Comment by vmaffei** [comment]
Hey @fanli-gcb I’ve updated the code in Part 5 once more. Let me know if it gives you any trouble!

**Comment by fanli-gcb** [comment]
Hi @vmaffei 
I think the last iteration (after the `for` loop) is needed. It runs the last batch. Something like:
```
BATCH=1377
for ((i=2, j=$((BATCH+1)); j<=$(head -n 1 ./genome_prediction/format/KEGG/trait_table.tab | wc -w); i=i+$BATCH, j=j+$BATCH));
do
	echo "$i - $j"
	# cat
	# cat
	# predict_traits
done;
j=$(head -n 1 ./genome_prediction/format/KEGG/trait_table.tab | wc -w)
echo "$i - $j"
# cat
# cat
# predict_trait
```

**Comment by vmaffei** [comment]
Ah, yes, the last iteration step is missing! I've added it here: https://github.com/vmaffei/dada2_to_picrust/tree/vmaffei-patch-1 

Thanks again for pointing that out! Let me know if this looks correct, and I'll merge it.

**Comment by fanli-gcb** [comment]
Looks good to me!

**Comment by vmaffei** [comment]
Thanks again! I'll close this for now, but feel free to reopen if needed.
