### ISSUE TITLE
TypeError: sample_counts.biom does not appear to be a BIOM file!

### ISSUE THREAD

**Issue by palomo11** [vmaffei/dada2_to_picrust#17]
Hi, 

First of all thanks for the nice pipeline.

I've running the pipeline without problems until Part 3, when it has called for the folowing error:

biom convert -i sample_counts.biom -o sample_counts.tab --to-tsv
"TypeError: sample_counts.biom does not appear to be a BIOM file!"

Here I attach the file:

I got that file by doing:

library(biomformat)
...
seqtab_biom <- t(seqtab.nochim)
seqtab_biom <- seqtab_biom[rownames(seqtab_biom)%in%db_out_filt$seqs,]
rownames(seqtab_biom) <- db_out_filt[db_out_filt$seqs%in%rownames(seqtab_biom),"ids"]
biom_object <- make_biom(data = seqtab_biom)
write_biom(biom_object, biom_file = "sample_counts.biom")

[sample_counts.biom.zip](https://github.com/vmaffei/dada2_to_picrust/files/1863174/sample_counts.biom.zip)

I hope you can help me with this.

Thanks in advance.

**Comment by vmaffei** [comment]
Hey, palomo11, make sure to use `library(biom)` by Joey instead of `library(biomformat)`

 Specifically, use the latest dev version of `biom`
```r
# install
library(devtools)
install_github("joey711/biom")
```
You only need to regenerate the sample_counts.biom file in Part 1 (so don't delete anything if you've already run everything else). Let me know if that works!

**Comment by palomo11** [comment]
Yes, it works! Thanks!

I had used biomformat because the first time I tried to install biom, it did not work. But now it is fine.

**Comment by vmaffei** [comment]
Good to hear! Let me know if you run into any further issues!
