### ISSUE TITLE
Problem with vsearch

### ISSUE THREAD

**Issue by marlenec** [vmaffei/dada2_to_picrust#18]
Hi,

I am trying the tutorial you provided to get metagenome PICRUST estimations from DADA2 output.
First part of the tutorial works fine, and I successfully intalled vsearch on my mac.
However when I am typing in R :
system('vsearch --usearch_global genome_prediction/gg_13_5_study_db.fasta.pre --db genome_prediction/97_otus.fasta --matched genome_prediction/gg_13_5_study_db.fasta --id 0.97')

I get the following error : 
vsearch v2.8.4_macos_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch
Fatal error: Unable to open matched output file for writing

I guess there is a problem with the file gg_13_5_study_db.fasta, which indeed does not exist because we didn't create it in previous steps of the tutorial. Or maybe I missed something ?

Thank you,

Marlene

**Comment by vmaffei** [comment]
Hi Marlene, are you still having trouble with vsearch? When you get a chance, run 
`sudo chmod a+w vsearch` 
This will give your vsearch binary write permissions. Retry the vsearch step afterwards. If you still have trouble, feel free to post back!

**Comment by marlenec** [comment]
Hi, thank you so much for your answer !
I tried :
`system('sudo chmod a+w vsearch --usearch_global genome_prediction/gg_13_5_study_db.fasta.pre --db genome_prediction/97_otus.fasta --matched genome_prediction/gg_13_5_study_db.fasta.pre --id 0.97')`
But  got this error :
> sudo: no tty present and no askpass program specified

So, after reading this subject on an ubuntu forum (https://askubuntu.com/questions/281742/sudo-no-tty-present-and-no-askpass-program-specified), I tried this :
`system('sudo -S ./binary vsearch --usearch_global genome_prediction/gg_13_5_study_db.fasta.pre --db genome_prediction/97_otus.fasta --matched genome_prediction/gg_13_5_study_db.fasta.pre --id 0.97')
`
R tried to run the command, but couldn't :
> Password:Error: Unable to establish connection with R session
> Error: Unable to establish connection with R session

I am trying to start R with sudo from the beginning... Let's see.

**Comment by vmaffei** [comment]
Whoops, let me clarify my instructions!

Outside of R, in a terminal window, navigate to your copy of ```vsearch``` and then type ```sudo chmod a+w vsearch```. This will give vsearch permission to write out data, if it already isn't allowed to do so. If no errors occur, reopen R and retry the vsearch step as written in the tutorial. No need to try anything like ```system('sudo chmod a+w vsearch...``` once back inside R.

Let me know how that goes for you!

**Comment by marlenec** [comment]
Hi,
I just tried this, and it seems to work !
Thank you a lot !

**Comment by vmaffei** [comment]
No problem! Please feel free to post any question you might have in the future!
