### ISSUE TITLE
The publication for this experimental pipeline

### ISSUE THREAD

**Issue by MarwaElnaiem** [vmaffei/dada2_to_picrust#20]
Hey, 

Thanks very much for this useful pipeline.
I would like to know if this pipeline has been published in an article or not? How it will be cited in my paper in case I used it? 

Regards,
Marwa

**Comment by vmaffei** [comment]
Hi Marwa, thanks for reaching out! There are no plans to develop this pipeline out of an experimental state (and hence no citable publication). Consider using PICRUSt2 instead: https://github.com/picrust/picrust2. PICRUSt2 performs the same function but uses a much improved pipeline and updated reference database. A citable pre-print for PICRUSt2 is available here: https://www.biorxiv.org/content/10.1101/672295v2. A peer-reviewed publication is also forthcoming in the next month or so.

**Comment by MarwaElnaiem** [comment]
Thanks very much for your reply.
I will try it.
