### ISSUE TITLE
elemental Q regarding input seq format 'seqtab.nochim.robj'

### ISSUE THREAD

**Issue by junhuili** [vmaffei/dada2_to_picrust#6]
I am wondering whether the input seq format must be 'robj'. If so, how can I convert 'fasta' to 'robf'? 

# grab study seqs
load(file = "genome_prediction/seqtab.nochim.robj")

**Comment by vmaffei** [comment]
Hi junhili, .robj is required for the pipeline as written, _but_ I am happy to write some example code for you to use a fasta. Were the sequences in the .fasta created by DADA2? If not, do you have a separate file that contains the number of times each sequence in the .fasta occurs in each sample? What software have you used up to this point?

**Comment by junhuili** [comment]
Hi Vince, many thanks for your prompt comments.  I just tried to proceed the seq using DADA2, it works.  Thank you!
